[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wordle"
path = "lib/mod.rs"

[[bin]]
name = "wordle"
path = "src/main.rs"

[dependencies]
